[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
azalea = { git = "https://github.com/mat-1/azalea" }
colored = "2.0.0"
dotenv = "0.15.0"
flume = "0.10.14"
fuzzy-matcher = "0.3.7"
lazy-regex = "2.5.0"
lazy_static = "1.4.0"
regex = "1.7.3"
serenity = { version = "0.11.5", default-features = false, features = [
    "builder",
    "client",
    "utils",
    "rustls_backend",
    "gateway",
    "http",
    "model",
    "cache",
] }
sorted-vec = "0.8.2"
thiserror = "1.0.40"
tokio = "1.27.0"
url = "2.3.1"

[dev-dependencies]
test-case = "3.1.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
