[workspace.package]
version = "0.1.0"
authors = ["Lily Smart <lily@neyoa.me>"]
edition = "2021"
description = "An Azalea + Serenity bot to synchronise Guild and Officer chats on the Hypixel network between Minecraft and Discord"
readme = "README.md"
repository = "https://github.com/itsneyoa/bridge-rs"
license = "AGPL-3.0-or-later"
publish = false

[workspace]
members = ["minecraft", "discord", "prelude", "sanitiser", "bridge"]

[profile.dev]
opt-level = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3
