[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
azalea = { git = "https://github.com/mat-1/azalea" }
colored = "2.0.0"
dotenv = "0.15.0"
flume = "0.10.14"
lazy-regex = "2.5.0"
serenity = { version = "0.11.5", default-features = false, features = [
    "builder",
    "client",
    "utils",
    "rustls_backend",
    "gateway",
    "http",
    "model",
] }
tokio = "1.27.0"
url = "2.3.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
