[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-broadcast = "0.5.1"
azalea = { git = "https://github.com/mat-1/azalea.git", default-features = false, rev = "22ea8c6" }
bevy_log = { version = "0.11.0", default-features = false }
colored = "2.0.0"
ctrlc = "3.2.5"
dotenv = "0.15.0"
futures = "0.3.28"
fuzzy-matcher = "0.3.7"
lazy-regex = "3.0.0"
log = { version = "0.4.19", features = ["std"] }
once_cell = "1.18.0"
rand = "0.8.5"
regex = "1.9.1"
serenity = { version = "0.11.5", default-features = false, features = [
    "builder",
    "client",
    "utils",
    "rustls_backend",
    "gateway",
    "http",
    "model",
    "cache",
] }
sorted-vec = "0.8.2"
thiserror = "1.0.40"
tokio = { version = "1.28.0", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
] }
url = "2.3.1"

[dev-dependencies]
test-case = "3.1.0"

[profile.dev]
opt-level = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3
